MACHINE LEARNING PIPELINE :-

Dataset

   ↓

Load Dataset

   ↓

Understand Dataset

   ↓

Clean Dataset

   ↓

EDA (Visualization)

   ↓

Feature Engineering

   ↓

Train-Test Split

   ↓

Train Model

   ↓

Prediction

   ↓

Evaluate Model

CSV = Comma Separated Values

In [20]:
# import
import pandas as pd

df = pd.read_csv("laptop_data.csv")

df.loc[(len(df)) ] = ['ASUS' ,	16,	512,	80000]
df.loc[(len(df)) ] = ['Lenovo' , 8,	256,	45000]

df.to_csv("laptop_data.csv")

print(df)

  Company  RAM   SSD   Price
0      HP    8   512   50000
1    Dell   16   512   75000
2   Apple   16  1024  150000
3    ASUS   16   512   80000
4  Lenovo    8   256   45000

In [12]:
df.head(2)

  Company  RAM  SSD  Price
0      HP    8  512  50000
1    Dell   16  512  75000

In [16]:
df.tail(3)

  Company  RAM   SSD   Price
2   Apple   16  1024  150000
3    ASUS   16   512   80000
4  Lenovo    8   256   45000

In [21]:
# Practice
import pandas as pd

df = pd.read_csv("laptop_data.csv")

df.head()


df.tail()

   Unnamed: 0 Company  RAM   SSD   Price
0           0      HP    8   512   50000
1           1    Dell   16   512   75000
2           2   Apple   16  1024  150000
3           3    ASUS   16   512   80000
4           4  Lenovo    8   256   45000

In [25]:
import numpy as np

a = [ 1 , 2 , 3 , 4 ]

b = [ 3 , 4 , 6 ,7]

c = [ 4 ,6 ,3 ,9]


arr = np.array([ a , b ,c])

print(arr)

[[1 2 3 4]
 [3 4 6 7]
 [4 6 3 9]]

# Lesson 2

In [42]:
import pandas as pd

df = pd.read_csv("data.csv")

df = df.drop(df.columns[0],axis = 1)
df.head()

,Unnamed: 0,brand,name,price,spec_rating,processor,CPU,Ram,Ram_type,ROM,ROM_type,GPU,display_size,resolution_width,resolution_height,OS,warranty
0,0,HP,Victus 15-fb0157AX Gaming Laptop,49900,73.000000,5th Gen AMD Ryzen 5 5600H,"Hexa Core, 12 Threads",8GB,DDR4,512GB,SSD,4GB AMD Radeon RX 6500M,15.6,1920.0,1080.0,Windows 11 OS,1
1,1,HP,15s-fq5007TU Laptop,39900,60.000000,12th Gen Intel Core i3 1215U,"Hexa Core (2P + 4E), 8 Threads",8GB,DDR4,512GB,SSD,Intel UHD Graphics,15.6,1920.0,1080.0,Windows 11 OS,1
2,2,Acer,One 14 Z8-415 Laptop,26990,69.323529,11th Gen Intel Core i3 1115G4,"Dual Core, 4 Threads",8GB,DDR4,512GB,SSD,Intel Iris Xe Graphics,14.0,1920.0,1080.0,Windows 11 OS,1
3,3,Lenovo,Yoga Slim 6 14IAP8 82WU0095IN Laptop,59729,66.000000,12th Gen Intel Core i5 1240P,"12 Cores (4P + 8E), 16 Threads",16GB,LPDDR5,512GB,SSD,Intel Integrated Iris Xe,14.0,2240.0,1400.0,Windows 11 OS,1
4,4,Apple,MacBook Air 2020 MGND3HN Laptop,69990,69.323529,Apple M1,Octa Core (4P + 4E),8GB,DDR4,256GB,SSD,Apple M1 Integrated Graphics,13.3,2560.0,1600.0,Mac OS,1

In [30]:
df.shape

(893, 18)

In [33]:
# most important fn.
import pandas as pd

df = pd.read_csv("data1.csv")
df.info() # work on all data

<class 'pandas.DataFrame'>
RangeIndex: 893 entries, 0 to 892
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.1  893 non-null    int64
 1   Unnamed: 0    893 non-null    int64
 2   brand         893 non-null    str
 3   name          893 non-null    str
 4   price         893 non-null    int64
 5   spec_rating   893 non-null    float64
 6   processor     893 non-null    str
 7   CPU           893 non-null    str
 8   Ram           893 non-null    str
 9   Ram_type      893 non-null    str
dtypes: float64(1), int64(3), str(6)
memory usage: 69.9 KB

In [43]:
df.describe() # provide detail only of

,Unnamed: 0,price,spec_rating,display_size,resolution_width,resolution_height,warranty
count,893.000000,893.000000,893.000000,893.000000,893.000000,893.000000,893.000000
mean,521.382979,79907.409854,69.379026,15.173751,2035.393057,1218.324748,1.079507
std,299.916605,60880.043823,5.541555,0.939095,426.076009,326.756883,0.326956
min,0.000000,9999.000000,60.000000,11.600000,1080.000000,768.000000,0.000000
25%,265.000000,44500.000000,66.000000,14.000000,1920.000000,1080.000000,1.000000
50%,531.000000,61990.000000,69.323529,15.600000,1920.000000,1080.000000,1.000000
75%,784.000000,90990.000000,71.000000,15.600000,1920.000000,1200.000000,1.000000
max,1019.000000,450039.000000,89.000000,18.000000,3840.000000,3456.000000,3.000000

In [44]:
df.columns

Index(['Unnamed: 0', 'brand', 'name', 'price', 'spec_rating', 'processor',
       'CPU', 'Ram', 'Ram_type', 'ROM', 'ROM_type', 'GPU', 'display_size',
       'resolution_width', 'resolution_height', 'OS', 'warranty'],
      dtype='str')

In [49]:
df.dtypes

Unnamed: 0             int64
brand                    str
name                     str
price                  int64
spec_rating          float64
processor                str
CPU                      str
Ram                      str
Ram_type                 str
ROM                      str
ROM_type                 str
GPU                      str
display_size         float64
resolution_width     float64
resolution_height    float64
OS                       str
warranty               int64
dtype: object

# Summary 
| Function        | Purpose                         |
| --------------- | ------------------------------- |
| `df.shape`      | Rows aur Columns batata hai     |
| `df.info()`     | Dataset ki complete information |
| `df.describe()` | Numerical statistics            |
| `df.columns`    | Column names                    |
| `df.dtypes`     | Har column ka data type         |

In [55]:
# Practice

import pandas as pd

df = pd.read_csv("practice/data.csv")

df.head()

    Name  Age  Salary
0   Aman   22   30000
1  Rahul   24   35000
2   Riya   23   40000

In [56]:
df.shape

(3, 3)

In [57]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str
 1   Age     3 non-null      int64
 2   Salary  3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes

In [58]:
df.describe()

        Age   Salary
count   3.0      3.0
mean   23.0  35000.0
std     1.0   5000.0
min    22.0  30000.0
25%    22.5  32500.0
50%    23.0  35000.0
75%    23.5  37500.0
max    24.0  40000.0

In [59]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [60]:
df.dtypes

Name        str
Age       int64
Salary    int64
dtype: object

# Lesson 3

Load Dataset
      ↓
Understand Dataset
      ↓
⭐ Data Cleaning   ← (Aaj ka topic)
      ↓
EDA
      ↓
Feature Engineering
      ↓
Train Model

In [3]:
import pandas as pd

df = pd.read_csv("data-cleaning.csv")

df.head()

  Company  RAM     Price
0      HP    8   50000.0
1    Dell   16       NaN
2   Apple   16  120000.0

In [7]:
df.isnull() # if value is missing reture true

   Company    RAM  Price
0    False  False  False
1    False  False   True
2    False  False  False

In [8]:
df.isnull().sum() # To count missing values in each column.

Company    0
RAM        0
Price      1
dtype: int64

In [9]:
df.dropna() # delete null values row , #### very important

  Company  RAM     Price
0      HP    8   50000.0
2   Apple   16  120000.0

In [11]:
df # it show 1 index values because i don't assign df.dropna() in this.

  Company  RAM     Price
0      HP    8   50000.0
1    Dell   16       NaN
2   Apple   16  120000.0

In [12]:
df.fillna('Value')

  Company  RAM     Price
0      HP    8   50000.0
1    Dell   16     Value
2   Apple   16  120000.0

In [13]:
df['Price'] = df['Price'].fillna(df['Price'].mean())

In [16]:
df

  Company  RAM     Price
0      HP    8   50000.0
1    Dell   16   85000.0
2   Apple   16  120000.0

In [19]:
# Duplicate
import pandas as pd

df = pd.read_csv("duplicate.csv")
df.head()

    Name  Age
0   Aman   22
1  Rahul   24
2  Rahul   24
3   Riya   23

In [23]:
df.duplicated() # return true if find duplicated values

0    False
1    False
2     True
3    False
dtype: bool

In [24]:
df.drop_duplicates() # delete duplicate values

    Name  Age
0   Aman   22
1  Rahul   24
3   Riya   23

In [22]:
df

    Name  Age
0   Aman   22
1  Rahul   24
2  Rahul   24
3   Riya   23

| Function            | Purpose               |
| ------------------- | --------------------- |
| `isnull()`          | Missing values check  |
| `isnull().sum()`    | Missing values count  |
| `dropna()`          | Missing rows remove   |
| `fillna()`          | Missing values fill   |
| `duplicated()`      | Duplicate rows check  |
| `drop_duplicates()` | Duplicate rows rmove |