# PANDAS
- THIS IS THE PYTHON LIBRARY.
- THAT USED FOR DATA CLEANING , DATA MANIPULATION AND DATA ANALYSIS.

In [2]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\amank\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\amank\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\amank\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\amank\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\amank\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [4]:
pd.__version__

'3.0.2'

In [5]:
# datafram => rows and columns  ke through banta h, basically table

In [6]:
# 1
# press shift + tab in
df = pd.DataFrame([11,22,33], columns= ['Col_name'])
print(df)

   Col_name
0        11
1        22
2        33

In [7]:
print(type(df))

<class 'pandas.DataFrame'>

In [8]:
data = {
    'Name': ['Madhav', 'Vishakha', 'Lalita', 'Rishabh'],
    'Age' : [16 , 17,18,19],
    'Salary': [90000, 70000 , 50000 , 30000]   
}

In [9]:
df = pd.DataFrame(data)
print(df)

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [10]:
# 2
df.tail(2) # head = top 5 rows , tail = bottom rows

      Name  Age  Salary
2   Lalita   18   50000
3  Rishabh   19   30000

In [11]:
df.shape

(4, 3)

In [12]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [13]:
df.rename(columns = {'Salary' : 'Monthly_Salary'} , inplace = True) # inplace matlab ki dataframe mein bhi change kar do

In [14]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [16]:
df.describe() # show statistical summary for numerical columm , mean , standard deviation

             Age  Monthly_Salary
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

In [17]:
# 3. Save and load data from csv

In [18]:
df.to_csv('Test_data.csv' ,index = False) # not need index , 0 , 1 ,2

In [19]:
load_csv = pd.read_csv('Test_data.csv')

In [20]:
load_csv

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [21]:
# 4. Rows and Columns = Selection

In [22]:
# select column
# df[['Name']]
df[['Name', 'Monthly_Salary']]

       Name  Monthly_Salary
0    Madhav           90000
1  Vishakha           70000
2    Lalita           50000
3   Rishabh           30000

In [23]:
df[['Name']]

       Name
0    Madhav
1  Vishakha
2    Lalita
3   Rishabh

In [24]:
# select rows 2 methods
df.loc[df.Name == 'Madhav']
df.loc[(df.Name=='Madhav') & (df.Monthly_Salary>=5000)]
# label based indexing , search based indexing

     Name  Age  Monthly_Salary
0  Madhav   16           90000

In [25]:
df.loc[0:2] # include 2 value # label based indexing

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000

In [26]:
# iloc - index-value based
df.iloc[0]
df.iloc[0:2] # not include 2 value. [start : stop : step]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000

In [27]:
# 5. filter dataframe

In [28]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [29]:
df_age_filter = df[df['Age'] >= 18]

In [30]:
df_age_filter

      Name  Age  Monthly_Salary
2   Lalita   18           50000
3  Rishabh   19           30000

In [31]:
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 50000)]

     Name  Age  Monthly_Salary
2  Lalita   18           50000

In [32]:
df_age_filter.to_csv('age_filter.csv' , index = False)

In [33]:
df.where(df['Age'] >= 18)

      Name   Age  Monthly_Salary
0      NaN   NaN             NaN
1      NaN   NaN             NaN
2   Lalita  18.0         50000.0
3  Rishabh  19.0         30000.0

In [34]:
df.where((df['Age'] >= 18) & (df['Monthly_Salary'] >= 40000), other = "Not Eligible") # use this to filter

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2        Lalita            18          50000
3  Not Eligible  Not Eligible   Not Eligible

In [35]:
# Rows and Columns - Operations(Add , Update , Delete) # Bookmark 34 minutes

In [36]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [37]:
# add new column 1
df['Team'] = ['CEO' , 'HR' , 'CTO' , 'DA']
df

       Name  Age  Monthly_Salary Team
0    Madhav   16           90000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3   Rishabh   19           30000   DA

In [38]:
df['Bonus'] = df['Monthly_Salary'] * 2
df

       Name  Age  Monthly_Salary Team   Bonus
0    Madhav   16           90000  CEO  180000
1  Vishakha   17           70000   HR  140000
2    Lalita   18           50000  CTO  100000
3   Rishabh   19           30000   DA   60000

In [39]:
# add new row
df.loc[len(df)] = ['ABC' , 21 , 21000 , 'IT' , 2000]
df

       Name  Age  Monthly_Salary Team   Bonus
0    Madhav   16           90000  CEO  180000
1  Vishakha   17           70000   HR  140000
2    Lalita   18           50000  CTO  100000
3   Rishabh   19           30000   DA   60000
4       ABC   21           21000   IT    2000

In [40]:
len(df)

5

In [41]:
# update value using index name
df.loc[0 , "Monthly_Salary"] = 95000
df

       Name  Age  Monthly_Salary Team   Bonus
0    Madhav   16           95000  CEO  180000
1  Vishakha   17           70000   HR  140000
2    Lalita   18           50000  CTO  100000
3   Rishabh   19           30000   DA   60000
4       ABC   21           21000   IT    2000

In [42]:
# Update value using column name
df.loc[df.Name == "Madhav" , 'Monthly_Salary']  = 91000
df

       Name  Age  Monthly_Salary Team   Bonus
0    Madhav   16           91000  CEO  180000
1  Vishakha   17           70000   HR  140000
2    Lalita   18           50000  CTO  100000
3   Rishabh   19           30000   DA   60000
4       ABC   21           21000   IT    2000

In [43]:
# Delete value - row and column values , 0 means row , 1 means columns

In [44]:
df.drop(df[df.Name == 'ABC'].index , inplace = True) # drop row , axis = 0

In [45]:
# df.drop("Madhav" , inplace = True)

In [46]:
df

       Name  Age  Monthly_Salary Team   Bonus
0    Madhav   16           91000  CEO  180000
1  Vishakha   17           70000   HR  140000
2    Lalita   18           50000  CTO  100000
3   Rishabh   19           30000   DA   60000

In [47]:
df[df.Name == 'ABC']

Empty DataFrame
Columns: [Name, Age, Monthly_Salary, Team, Bonus]
Index: []

In [48]:
df.drop('Bonus' , axis = 1 , inplace = True) # 1 = columns

In [49]:
df

       Name  Age  Monthly_Salary Team
0    Madhav   16           91000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3   Rishabh   19           30000   DA

In [50]:
# df.drop(['Bonus' , 'Team'] , axis = 1] # 1 means columns

In [51]:
df

       Name  Age  Monthly_Salary Team
0    Madhav   16           91000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3   Rishabh   19           30000   DA

In [52]:
df.drop(1 , axis = 0)

      Name  Age  Monthly_Salary Team
0   Madhav   16           91000  CEO
2   Lalita   18           50000  CTO
3  Rishabh   19           30000   DA

In [53]:
# sort values in ascentding , descentding
df.sort_values('Monthly_Salary' , inplace = True)

In [54]:
df.sort_values('Age' , inplace = True)

In [55]:
df

       Name  Age  Monthly_Salary Team
0    Madhav   16           91000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3   Rishabh   19           30000   DA

In [56]:
# 7 woring with data values

In [57]:
df

       Name  Age  Monthly_Salary Team
0    Madhav   16           91000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3   Rishabh   19           30000   DA

In [58]:
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03']

In [59]:
df

       Name  Age  Monthly_Salary Team         DOJ
0    Madhav   16           91000  CEO  2024-01-01
1  Vishakha   17           70000   HR  2024-01-15
2    Lalita   18           50000  CTO  2024-03-28
3   Rishabh   19           30000   DA  2024-03-03

In [60]:
df['DOJ'].dtype

In [61]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [62]:
df['DOJ'].dtype

dtype('<M8[us]')

In [63]:
df

       Name  Age  Monthly_Salary Team        DOJ
0    Madhav   16           91000  CEO 2024-01-01
1  Vishakha   17           70000   HR 2024-01-15
2    Lalita   18           50000  CTO 2024-03-28
3   Rishabh   19           30000   DA 2024-03-03

In [64]:
df1 = df

In [65]:
df1

       Name  Age  Monthly_Salary Team        DOJ
0    Madhav   16           91000  CEO 2024-01-01
1  Vishakha   17           70000   HR 2024-01-15
2    Lalita   18           50000  CTO 2024-03-28
3   Rishabh   19           30000   DA 2024-03-03

In [66]:
df1['DOJ2'] = ['01-01-2025', '15-01-2025', '28-03-2025', '03-03-2025']

In [67]:
df1['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03']

In [68]:
df1['DOJ2'].dtype

In [69]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'] , format = '%d-%m-%Y') # Y means full year

In [70]:
df1['DOJ2'].dtype

dtype('<M8[us]')

In [71]:
# df = df.drop('DOJ2' , axis  = 1)

In [72]:
df

       Name  Age  Monthly_Salary Team         DOJ       DOJ2
0    Madhav   16           91000  CEO  2024-01-01 2025-01-01
1  Vishakha   17           70000   HR  2024-01-15 2025-01-15
2    Lalita   18           50000  CTO  2024-03-28 2025-03-28
3   Rishabh   19           30000   DA  2024-03-03 2025-03-03

In [73]:
df

       Name  Age  Monthly_Salary Team         DOJ       DOJ2
0    Madhav   16           91000  CEO  2024-01-01 2025-01-01
1  Vishakha   17           70000   HR  2024-01-15 2025-01-15
2    Lalita   18           50000  CTO  2024-03-28 2025-03-28
3   Rishabh   19           30000   DA  2024-03-03 2025-03-03

In [75]:
df = df.drop('DOJ2' , axis = 1)
df

       Name  Age  Monthly_Salary Team         DOJ
0    Madhav   16           91000  CEO  2024-01-01
1  Vishakha   17           70000   HR  2024-01-15
2    Lalita   18           50000  CTO  2024-03-28
3   Rishabh   19           30000   DA  2024-03-03

In [78]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [79]:
df['DOJ'].dtype

dtype('<M8[us]')

In [83]:
df['DOJ'].dt.month
df['DOJ'].dt.day
df['DOJ'].dt.day_name()

0      Monday
1      Monday
2    Thursday
3      Sunday
Name: DOJ, dtype: str

In [84]:
df['Month'] = df['DOJ'].dt.month

In [85]:
df

       Name  Age  Monthly_Salary Team        DOJ  Month
0    Madhav   16           91000  CEO 2024-01-01      1
1  Vishakha   17           70000   HR 2024-01-15      1
2    Lalita   18           50000  CTO 2024-03-28      3
3   Rishabh   19           30000   DA 2024-03-03      3

In [86]:
df['DOJ'] + pd.Timedelta(days = 90)

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
Name: DOJ, dtype: datetime64[us]

In [87]:
# 8. Handling Missing Values

In [88]:
df

       Name  Age  Monthly_Salary Team        DOJ  Month
0    Madhav   16           91000  CEO 2024-01-01      1
1  Vishakha   17           70000   HR 2024-01-15      1
2    Lalita   18           50000  CTO 2024-03-28      3
3   Rishabh   19           30000   DA 2024-03-03      3

In [89]:
df.isnull()

    Name    Age  Monthly_Salary   Team    DOJ  Month
0  False  False           False  False  False  False
1  False  False           False  False  False  False
2  False  False           False  False  False  False
3  False  False           False  False  False  False

In [97]:
import numpy as np

In [107]:
df.loc[df.Name == 'Rishabh' , 'Salary'] = np.nan

In [109]:
df.rename(columns={'Monthly_Salary': 'Salary'}, inplace=True)

In [112]:
df

       Name  Age  Salary Team         DOJ       DOJ2  Salary
0    Madhav   16   91000  CEO  2024-01-01 2025-01-01     NaN
1  Vishakha   17   70000   HR  2024-01-15 2025-01-15     NaN
2    Lalita   18   50000  CTO  2024-03-28 2025-03-28     NaN
3   Rishabh   19   30000   DA  2024-03-03 2025-03-03     NaN

In [115]:
df

       Name  Age  Salary Team         DOJ       DOJ2  Salary
0    Madhav   16   91000  CEO  2024-01-01 2025-01-01     NaN
1  Vishakha   17   70000   HR  2024-01-15 2025-01-15     NaN
2    Lalita   18   50000  CTO  2024-03-28 2025-03-28     NaN
3   Rishabh   19   30000   DA  2024-03-03 2025-03-03     NaN

In [121]:
df.drop('DOJ2' , axis = 1 , inplace = True)

In [122]:
df.drop(Salary

       Name  Age  Salary Team         DOJ  Salary
0    Madhav   16   91000  CEO  2024-01-01     NaN
1  Vishakha   17   70000   HR  2024-01-15     NaN
2    Lalita   18   50000  CTO  2024-03-28     NaN
3   Rishabh   19   30000   DA  2024-03-03     NaN

In [123]:
df = df.loc[:, ~df.columns.duplicated(keep='first')]
df

       Name  Age  Salary Team         DOJ
0    Madhav   16   91000  CEO  2024-01-01
1  Vishakha   17   70000   HR  2024-01-15
2    Lalita   18   50000  CTO  2024-03-28
3   Rishabh   19   30000   DA  2024-03-03

In [124]:
df.loc[df.Name == 'Rishabh' , 'Salary'] = np.nan

In [125]:
df

       Name  Age   Salary Team         DOJ
0    Madhav   16  91000.0  CEO  2024-01-01
1  Vishakha   17  70000.0   HR  2024-01-15
2    Lalita   18  50000.0  CTO  2024-03-28
3   Rishabh   19      NaN   DA  2024-03-03

In [129]:
df.isnull().sum()

Name      0
Age       0
Salary    1
Team      0
DOJ       0
dtype: int64

In [132]:
df = df.fillna(0)

In [133]:
df

       Name  Age   Salary Team         DOJ
0    Madhav   16  91000.0  CEO  2024-01-01
1  Vishakha   17  70000.0   HR  2024-01-15
2    Lalita   18  50000.0  CTO  2024-03-28
3   Rishabh   19      0.0   DA  2024-03-03

In [137]:
df.loc[df.Name == 'Rishabh', 'Salary'] = 30000

In [141]:
df = df.drop('Rishabh')

In [142]:
df

       Name   Age   Salary Team         DOJ
0    Madhav  16.0  91000.0  CEO  2024-01-01
1  Vishakha  17.0  70000.0   HR  2024-01-15
2    Lalita  18.0  50000.0  CTO  2024-03-28
3   Rishabh  19.0  30000.0   DA  2024-03-03

In [143]:
# 9
import dill
# पूरी नोटबुक का स्टेट 'notebook_env.db' फाइल में सेव करें
dill.dump_session('notebook_env.db')

ModuleNotFoundError: No module named 'dill'

In [1]:
df

NameError: name 'df' is not defined

In [1]:
import dill
# सेव किया हुआ स्टेट वापस लोड करें
dill.load_session('notebook_env.db')

In [2]:
df

       Name   Age   Salary Team         DOJ
0    Madhav  16.0  91000.0  CEO  2024-01-01
1  Vishakha  17.0  70000.0   HR  2024-01-15
2    Lalita  18.0  50000.0  CTO  2024-03-28
3   Rishabh  19.0  30000.0   DA  2024-03-03

In [7]:
df['DOJ'].dtype

dtype('<M8[us]')

In [6]:
df['DOJ']= pd.to_datetime(df['DOJ'])

In [8]:
df['Month'] = df['DOJ'].dt.month

In [9]:
df

       Name   Age   Salary Team        DOJ  Month
0    Madhav  16.0  91000.0  CEO 2024-01-01      1
1  Vishakha  17.0  70000.0   HR 2024-01-15      1
2    Lalita  18.0  50000.0  CTO 2024-03-28      3
3   Rishabh  19.0  30000.0   DA 2024-03-03      3

In [10]:
df['Month'].value_counts()

Month
1    2
3    2
Name: count, dtype: int64

In [11]:
df[df['Month'] == 1].value_counts()

Name      Age   Salary   Team  DOJ         Month
Madhav    16.0  91000.0  CEO   2024-01-01  1        1
Vishakha  17.0  70000.0  HR    2024-01-15  1        1
Name: count, dtype: int64

In [13]:
df.groupby('Month')['Salary'].mean()

Month
1    80500.0
3    40000.0
Name: Salary, dtype: float64

In [14]:
df.groupby('Month').agg({'Salary':'mean' , 'Name':'count'})

        Salary  Name
Month
1      80500.0     2
3      40000.0     2

In [15]:
# 10  Concatenate(copy paste) and merge

In [16]:
df1 = pd.DataFrame({'ID' : [1,2,3] , 'Name' : ['A','B','C']})
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [17]:
df2 = pd.DataFrame({'ID' : [1,2,2,4] , 'Score' : [88,96,77,79]})
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [20]:
pd.concat([df1,df2] , axis = 0) # vertical / row level / top on top
pd.concat([df1,df2] , axis = 1) # Horizantal/ column level / side on side

    ID Name  ID  Score
0  1.0    A   1     88
1  2.0    B   2     96
2  3.0    C   2     77
3  NaN  NaN   4     79

In [24]:
# merge = join
pd.merge(df1 , df2 , how = 'inner' , on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [25]:
pd.merge(df1 , df2 , how = 'inner' , left_on = 'ID' , right_on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [ ]:
# AI AND CHATGPT