In [1]:
import pandas as pd

In [2]:
 df = pd.DataFrame([11,221,34] , columns = ['Numbers'])

In [3]:
df

   Numbers
0       11
1      221
2       34

In [4]:
df[(df['Numbers'] == 34)]

   Numbers
2       34

In [5]:
print(type(df))

<class 'pandas.DataFrame'>

In [6]:
data = {
    'Name': ['Madhav', 'Vishakha', 'Lalita', 'Rishabh'],
    'Age': [16,17,18,19],
    'Salary': [90000, 70000, 50000, 30000]
}

In [ ]:
df = pd.DataFrame(data)
df

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [8]:
df[df['Name'] == 'Lalita'].Salary

2    50000
Name: Salary, dtype: int64

In [9]:
df.shape

(4, 3)

In [10]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [11]:
df.rename(columns = {'Salary' : 'Monthly_Salary'} , inplace = True)

In [12]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [14]:
df.describe()

             Age  Monthly_Salary
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

In [15]:
df.to_csv(r'C:\Users\amank\Desktop\sem\Practice_Result.csv' , index = False)

In [16]:
df.rename( columns = { 'Character Name'  : 'Name'} , inplace = True)

In [17]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [18]:
df1 = pd.read_csv(r"C:\Users\amank\Desktop\sem\Practice_Result.csv")

In [19]:
df1

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [20]:
df['Name']

0      Madhav
1    Vishakha
2      Lalita
3     Rishabh
Name: Name, dtype: str

In [21]:
df[['Name']] # select sinlge column

       Name
0    Madhav
1  Vishakha
2    Lalita
3   Rishabh

In [22]:
df[['Name' , 'Monthly_Salary']]

       Name  Monthly_Salary
0    Madhav           90000
1  Vishakha           70000
2    Lalita           50000
3   Rishabh           30000

In [23]:
df.loc[df.Name == 'Madhav']

     Name  Age  Monthly_Salary
0  Madhav   16           90000

In [24]:
df[df['Name'] == 'Madhav']

     Name  Age  Monthly_Salary
0  Madhav   16           90000

In [25]:
df.loc[(df.Name == "Madhav") & (df.Age == 16)]

     Name  Age  Monthly_Salary
0  Madhav   16           90000

In [26]:
df.loc[0:2]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000

In [27]:
df.iloc[0:2]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000

In [28]:
df.loc[(df.Name == "Madhav") & (df.Age >= 10)]

     Name  Age  Monthly_Salary
0  Madhav   16           90000

In [29]:
# Filter  Values

In [30]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [31]:
df.rename(columns = {'Monthly_Salary': 'Salary'}, inplace = True)

In [32]:
df

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [33]:
df_age_filter = df[df['Age'] >= 18]

In [34]:
df_age_filter

      Name  Age  Salary
2   Lalita   18   50000
3  Rishabh   19   30000

In [35]:
df[(df['Age'] >= 18) & (df['Salary'] >= 45000)]

     Name  Age  Salary
2  Lalita   18   50000

In [36]:
df.where((df.Age >= 18) & (df.Salary >= 45000) , other = '-')

     Name Age Salary
0       -   -      -
1       -   -      -
2  Lalita  18  50000
3       -   -      -

In [37]:
df

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [38]:
df

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [39]:
df['Team'] = [ 1 , 2, 3 , 4]

In [40]:
df

       Name  Age  Salary  Team
0    Madhav   16   90000     1
1  Vishakha   17   70000     2
2    Lalita   18   50000     3
3   Rishabh   19   30000     4

In [41]:
df['Bonus'] = df['Salary'] * 4

In [42]:
df

       Name  Age  Salary  Team   Bonus
0    Madhav   16   90000     1  360000
1  Vishakha   17   70000     2  280000
2    Lalita   18   50000     3  200000
3   Rishabh   19   30000     4  120000

In [43]:
df.loc[len(df)] = [ "Raju" , 2 , 4 , 'Dholokpur' , 8]

In [44]:
df

       Name  Age  Salary       Team   Bonus
0    Madhav   16   90000          1  360000
1  Vishakha   17   70000          2  280000
2    Lalita   18   50000          3  200000
3   Rishabh   19   30000          4  120000
4      Raju    2       4  Dholokpur       8

In [45]:
df.drop(df[df.Team == 5].index , axis = 0 ,  inplace = True)

In [46]:
df

       Name  Age  Salary       Team   Bonus
0    Madhav   16   90000          1  360000
1  Vishakha   17   70000          2  280000
2    Lalita   18   50000          3  200000
3   Rishabh   19   30000          4  120000
4      Raju    2       4  Dholokpur       8

In [47]:
df.loc[5, 'Team'] = 5

In [70]:
df

       Name   Age   Salary       Team     Bonus
0    Madhav  16.0  90000.0          1  360000.0
1  Vishakha  17.0  70000.0          2  280000.0
2    Lalita  18.0  50000.0          3  200000.0
3   Rishabh  19.0  30000.0          4  120000.0
4      Raju   2.0   9999.0  Dholokpur    9999.0
5       NaN   NaN      NaN          5       NaN

In [49]:
df.loc[df.Name == 'Raju' , 'Salary'] = 9999

In [50]:
df.loc[df.Name == 'Raju' , 'Bonus'] = df['Salary'] * 1

In [72]:
df = df.drop(df[df.Team == 5].index)

In [73]:
df

       Name   Age   Salary       Team     Bonus
0    Madhav  16.0  90000.0          1  360000.0
1  Vishakha  17.0  70000.0          2  280000.0
2    Lalita  18.0  50000.0          3  200000.0
3   Rishabh  19.0  30000.0          4  120000.0
4      Raju   2.0   9999.0  Dholokpur    9999.0

In [74]:
df.drop(1, axis=0)

      Name   Age   Salary       Team     Bonus
0   Madhav  16.0  90000.0          1  360000.0
2   Lalita  18.0  50000.0          3  200000.0
3  Rishabh  19.0  30000.0          4  120000.0
4     Raju   2.0   9999.0  Dholokpur    9999.0

In [75]:
df.drop('Bonus', axis = 1, inplace = True)

In [76]:
df

       Name   Age   Salary       Team
0    Madhav  16.0  90000.0          1
1  Vishakha  17.0  70000.0          2
2    Lalita  18.0  50000.0          3
3   Rishabh  19.0  30000.0          4
4      Raju   2.0   9999.0  Dholokpur

In [77]:
df.drop(4,axis = 0)

       Name   Age   Salary Team
0    Madhav  16.0  90000.0    1
1  Vishakha  17.0  70000.0    2
2    Lalita  18.0  50000.0    3
3   Rishabh  19.0  30000.0    4

In [83]:
df.loc[len(df)] = ['Ak' , 20 , 89000, 6] # input

In [87]:
df =df.drop(5, axis = 0)

In [91]:
df = df.drop(4, axis = 0)

In [92]:
df

       Name   Age   Salary Team
0    Madhav  16.0  90000.0    1
1  Vishakha  17.0  70000.0    2
2    Lalita  18.0  50000.0    3
3   Rishabh  19.0  30000.0    4

In [94]:
df.sort_values('Salary' , ascending = False)

       Name   Age   Salary Team
0    Madhav  16.0  90000.0    1
1  Vishakha  17.0  70000.0    2
2    Lalita  18.0  50000.0    3
3   Rishabh  19.0  30000.0    4

In [95]:
df.loc[len(df)] = ['Ak' ,20 , 10000000 , 5]

In [96]:
df

       Name   Age      Salary Team
0    Madhav  16.0     90000.0    1
1  Vishakha  17.0     70000.0    2
2    Lalita  18.0     50000.0    3
3   Rishabh  19.0     30000.0    4
4        Ak  20.0  10000000.0    5

In [99]:
df.sort_values('Salary' , ascending = False)

       Name   Age      Salary Team
4        Ak  20.0  10000000.0    5
0    Madhav  16.0     90000.0    1
1  Vishakha  17.0     70000.0    2
2    Lalita  18.0     50000.0    3
3   Rishabh  19.0     30000.0    4

In [106]:
df = df.drop(df[df.Name == 'Ak'].index)

In [107]:
df['DOJ'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03']
df

       Name   Age   Salary Team         DOJ
0    Madhav  16.0  90000.0    1  2024-01-01
1  Vishakha  17.0  70000.0    2  2024-01-15
2    Lalita  18.0  50000.0    3  2024-03-28
3   Rishabh  19.0  30000.0    4  2024-03-03

In [108]:
df

       Name   Age   Salary Team         DOJ
0    Madhav  16.0  90000.0    1  2024-01-01
1  Vishakha  17.0  70000.0    2  2024-01-15
2    Lalita  18.0  50000.0    3  2024-03-28
3   Rishabh  19.0  30000.0    4  2024-03-03

In [109]:
df['DOJ'].dtype

In [110]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [111]:
df

       Name   Age   Salary Team        DOJ
0    Madhav  16.0  90000.0    1 2024-01-01
1  Vishakha  17.0  70000.0    2 2024-01-15
2    Lalita  18.0  50000.0    3 2024-03-28
3   Rishabh  19.0  30000.0    4 2024-03-03

In [112]:
df['DOJ'].dtype

dtype('<M8[us]')

In [113]:
df['DOJ2'] = [ '01-01-2025', '15-01-2025', '28-03-2025', '03-03-2025']

In [114]:
df

       Name   Age   Salary Team        DOJ        DOJ2
0    Madhav  16.0  90000.0    1 2024-01-01  01-01-2025
1  Vishakha  17.0  70000.0    2 2024-01-15  15-01-2025
2    Lalita  18.0  50000.0    3 2024-03-28  28-03-2025
3   Rishabh  19.0  30000.0    4 2024-03-03  03-03-2025

In [120]:
df['DOJ2'].dtype

dtype('<M8[us]')

In [119]:
df['DOJ2'] = pd.to_datetime(df['DOJ2'] , format = '%d-%m-%Y')

In [121]:
df1 = df

In [122]:
df1

       Name   Age   Salary Team        DOJ       DOJ2
0    Madhav  16.0  90000.0    1 2024-01-01 2025-01-01
1  Vishakha  17.0  70000.0    2 2024-01-15 2025-01-15
2    Lalita  18.0  50000.0    3 2024-03-28 2025-03-28
3   Rishabh  19.0  30000.0    4 2024-03-03 2025-03-03

In [124]:
df.loc[0,'DOJ2'] = '2033-03-03'

In [125]:
df

       Name   Age   Salary Team        DOJ       DOJ2
0    Madhav  16.0  90000.0    1 2024-01-01 2033-03-03
1  Vishakha  17.0  70000.0    2 2024-01-15 2025-01-15
2    Lalita  18.0  50000.0    3 2024-03-28 2025-03-28
3   Rishabh  19.0  30000.0    4 2024-03-03 2025-03-03

In [126]:
df1

       Name   Age   Salary Team        DOJ       DOJ2
0    Madhav  16.0  90000.0    1 2024-01-01 2033-03-03
1  Vishakha  17.0  70000.0    2 2024-01-15 2025-01-15
2    Lalita  18.0  50000.0    3 2024-03-28 2025-03-28
3   Rishabh  19.0  30000.0    4 2024-03-03 2025-03-03

In [129]:
df2 = df.copy()

In [130]:
df2

       Name   Age   Salary Team        DOJ       DOJ2
0    Madhav  16.0  90000.0    1 2024-01-01 2033-03-03
1  Vishakha  17.0  70000.0    2 2024-01-15 2025-01-15
2    Lalita  18.0  50000.0    3 2024-03-28 2025-03-28
3   Rishabh  19.0  30000.0    4 2024-03-03 2025-03-03

In [131]:
df.loc[1,'DOJ2'] = '2044-04-22'

In [132]:
df

       Name   Age   Salary Team        DOJ       DOJ2
0    Madhav  16.0  90000.0    1 2024-01-01 2033-03-03
1  Vishakha  17.0  70000.0    2 2024-01-15 2044-04-22
2    Lalita  18.0  50000.0    3 2024-03-28 2025-03-28
3   Rishabh  19.0  30000.0    4 2024-03-03 2025-03-03

In [133]:
df1

       Name   Age   Salary Team        DOJ       DOJ2
0    Madhav  16.0  90000.0    1 2024-01-01 2033-03-03
1  Vishakha  17.0  70000.0    2 2024-01-15 2044-04-22
2    Lalita  18.0  50000.0    3 2024-03-28 2025-03-28
3   Rishabh  19.0  30000.0    4 2024-03-03 2025-03-03

In [134]:
df2

       Name   Age   Salary Team        DOJ       DOJ2
0    Madhav  16.0  90000.0    1 2024-01-01 2033-03-03
1  Vishakha  17.0  70000.0    2 2024-01-15 2025-01-15
2    Lalita  18.0  50000.0    3 2024-03-28 2025-03-28
3   Rishabh  19.0  30000.0    4 2024-03-03 2025-03-03

In [135]:
df

       Name   Age   Salary Team        DOJ       DOJ2
0    Madhav  16.0  90000.0    1 2024-01-01 2033-03-03
1  Vishakha  17.0  70000.0    2 2024-01-15 2044-04-22
2    Lalita  18.0  50000.0    3 2024-03-28 2025-03-28
3   Rishabh  19.0  30000.0    4 2024-03-03 2025-03-03

In [142]:
df.drop('DOJ2' ,axis = 1 , inplace = True)

In [143]:
df

       Name   Age   Salary Team        DOJ
0    Madhav  16.0  90000.0    1 2024-01-01
1  Vishakha  17.0  70000.0    2 2024-01-15
2    Lalita  18.0  50000.0    3 2024-03-28
3   Rishabh  19.0  30000.0    4 2024-03-03

In [148]:
df['Month']  = df['DOJ'].dt.month

In [149]:
df

       Name   Age   Salary Team        DOJ  Month
0    Madhav  16.0  90000.0    1 2024-01-01      1
1  Vishakha  17.0  70000.0    2 2024-01-15      1
2    Lalita  18.0  50000.0    3 2024-03-28      3
3   Rishabh  19.0  30000.0    4 2024-03-03      3

In [152]:
df['Retirement date'] = df['DOJ'] + pd.Timedelta(weeks = 1565)

In [153]:
df

       Name   Age   Salary Team        DOJ  Month Retirement date
0    Madhav  16.0  90000.0    1 2024-01-01      1      2053-12-29
1  Vishakha  17.0  70000.0    2 2024-01-15      1      2054-01-12
2    Lalita  18.0  50000.0    3 2024-03-28      3      2054-03-26
3   Rishabh  19.0  30000.0    4 2024-03-03      3      2054-03-01

In [157]:
df.drop('Month' , axis = 1 , inplace = True)

In [158]:
df

       Name   Age   Salary Team        DOJ Retirement date
0    Madhav  16.0  90000.0    1 2024-01-01      2053-12-29
1  Vishakha  17.0  70000.0    2 2024-01-15      2054-01-12
2    Lalita  18.0  50000.0    3 2024-03-28      2054-03-26
3   Rishabh  19.0  30000.0    4 2024-03-03      2054-03-01

In [161]:
df

       Name   Age   Salary Team        DOJ Retirement date
0    Madhav  16.0  90000.0    1 2024-01-01      2053-12-29
1  Vishakha  17.0  70000.0    2 2024-01-15      2054-01-12
2    Lalita  18.0  50000.0    3 2024-03-28      2054-03-26
3   Rishabh  19.0  30000.0    4 2024-03-03      2054-03-01

In [162]:
import numpy as np

In [167]:
df.loc[df.Name == 'Madhav' , 'Salary'] = 67

AttributeError: 'float' object has no attribute 'loc'

In [169]:
df1

       Name   Age   Salary Team        DOJ Retirement date
0    Madhav  16.0      NaN    1 2024-01-01      2053-12-29
1  Vishakha  17.0  70000.0    2 2024-01-15      2054-01-12
2    Lalita  18.0  50000.0    3 2024-03-28      2054-03-26
3   Rishabh  19.0  30000.0    4 2024-03-03      2054-03-01

In [170]:
df

nan

In [171]:
df1

       Name   Age   Salary Team        DOJ Retirement date
0    Madhav  16.0      NaN    1 2024-01-01      2053-12-29
1  Vishakha  17.0  70000.0    2 2024-01-15      2054-01-12
2    Lalita  18.0  50000.0    3 2024-03-28      2054-03-26
3   Rishabh  19.0  30000.0    4 2024-03-03      2054-03-01

In [172]:
df = df1

In [173]:
df

       Name   Age   Salary Team        DOJ Retirement date
0    Madhav  16.0      NaN    1 2024-01-01      2053-12-29
1  Vishakha  17.0  70000.0    2 2024-01-15      2054-01-12
2    Lalita  18.0  50000.0    3 2024-03-28      2054-03-26
3   Rishabh  19.0  30000.0    4 2024-03-03      2054-03-01

In [174]:
df.isnull()

    Name    Age  Salary   Team    DOJ  Retirement date
0  False  False    True  False  False            False
1  False  False   False  False  False            False
2  False  False   False  False  False            False
3  False  False   False  False  False            False

In [175]:
df[df.isnull()]

  Name  Age  Salary Team DOJ Retirement date
0  NaN  NaN     NaN  NaN NaT             NaT
1  NaN  NaN     NaN  NaN NaT             NaT
2  NaN  NaN     NaN  NaN NaT             NaT
3  NaN  NaN     NaN  NaN NaT             NaT

In [176]:
df

       Name   Age   Salary Team        DOJ Retirement date
0    Madhav  16.0      NaN    1 2024-01-01      2053-12-29
1  Vishakha  17.0  70000.0    2 2024-01-15      2054-01-12
2    Lalita  18.0  50000.0    3 2024-03-28      2054-03-26
3   Rishabh  19.0  30000.0    4 2024-03-03      2054-03-01

In [177]:
df.to_csv('Save Data.csv')

In [178]:
df

       Name   Age   Salary Team        DOJ Retirement date
0    Madhav  16.0      NaN    1 2024-01-01      2053-12-29
1  Vishakha  17.0  70000.0    2 2024-01-15      2054-01-12
2    Lalita  18.0  50000.0    3 2024-03-28      2054-03-26
3   Rishabh  19.0  30000.0    4 2024-03-03      2054-03-01

In [180]:
df.isnull().sum()

Name               0
Age                0
Salary             1
Team               0
DOJ                0
Retirement date    0
dtype: int64

In [181]:
df.fillna(9)

       Name   Age   Salary Team        DOJ Retirement date
0    Madhav  16.0      9.0    1 2024-01-01      2053-12-29
1  Vishakha  17.0  70000.0    2 2024-01-15      2054-01-12
2    Lalita  18.0  50000.0    3 2024-03-28      2054-03-26
3   Rishabh  19.0  30000.0    4 2024-03-03      2054-03-01

In [186]:
df['Name'].value_count()

AttributeError: 'Series' object has no attribute 'value_count'